# Start from the latest Golang base image
FROM golang:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Set the GOPROXY environment variable (Optional, but helps to speed up the build)
ENV GOPROXY=https://proxy.golang.org

# Build the Go app
RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
