version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_DSN=root:root@tcp(mysql:3306)/testdb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-ui
    ports:
      - "3000:80"
    depends_on:
      - backend
